CoreConfiguration:
    DefaultBrowser: Chrome

ScreenshotTaker:
    Margin: 5
    ScreenshotTakeHorizontalOverlap: 35
    ScreenshotTakeVerticalOverlap: 35

VisualRegression:
    ScreenshotDiffTolerance: 1%
    ScreenshotStorePath: c:\ScreenshotStore
    ScreenshotStoreFileExtension: .png
    ScreenshotStoreBaseVersionId: base
    ScreenshotStoreReferenceVersionId: ref
    ScreenshotStoreDiffVersionId: diff