DefaultBrowser: Opera

ScreenshotDiffTolerance: 1%
ScreenshotStorePath: c:\ScreenshotStore
ScreenshotStoreFileExtension: .png
ScreenshotStoreBaseVersionId: base
ScreenshotStoreReferenceVersionId: ref
ScreenshotStoreDiffVersionId: diff